### PR TITLE
Adds the possibility to filter learning plans by cohorts

### PR DESCRIPTION
**Pull request by abias**
The patch was originally implemented by LMSACE <info@lmsace.com> and is now polished and contributed to upstream by Moodle Partner lern.link.

### CODE REVIEW

**Comment by levemar** [comment]
Hi @abias!
Thank you for your contribution! We will take a closer look and get back to you as soon as possible. However, it might takes a few weeks.
Thanks,
Marie-Eve

**Comment by abias** [comment]
Hi @levemar , 

do you have any news regarding this PR?

Thanks,
Alex

**Comment by levemar** [comment]
Hi @abias !

I am really sorry for taking so much time to answer to your pull request. Here are some comments of things to correct before we can integrate it : 

* Can you rebase it on our most recent master? (sorry about that, we had some other modifications in the meantime...)
* When we first load the page, the "Cohort" filter should be disabled like the other choices
image
* Add the new language strings in alphabetical order instead of at the end of the file (in lang/en/report_lpmonitoring.php)
* In db/services.php restrict the function by adding a capability (an existing capability like moodle/competency:templateview maybe?)
* Why are there empty parenthesis next to the cohort name?
image
* Can you add at least one unit test that covers your code (at the minimum : create 2 cohorts with the same learning plan template, and when you filter make sure you get only students from the selected cohort, or something like that)
* If you can add a behat test, it is even better!

Once you do the modifications, I will make sure we answer faster this time, so it doesn't takes months to integrate your patch. Sorry again for the delay!

Marie-Eve

**Comment by abias** [comment]
Hi @levemar ,

thank you for your extensive feedback!
And no worries about the delay, I can understand you very well.

> Can you rebase it on our most recent master? (sorry about that, we had some other modifications in the meantime...)

Sure!

>     When we first load the page, the "Cohort" filter should be disabled like the other choices

I will try to understand how the other choices behave and will the adapt the cohort filter accordingly.

>    Add the new language strings in alphabetical order instead of at the end of the file (in lang/en/report_lpmonitoring.php)

Sure!

>    In db/services.php restrict the function by adding a capability (an existing capability like moodle/competency:templateview maybe?)

OK, I will do that.

>     Why are there empty parenthesis next to the cohort name?

I have seen these parenthesis as well in the GUI based on the patch by LMSACE, but I was not able to find the reason for them. I will look further with the goal to remove them.

>    Can you add at least one unit test that covers your code (at the minimum : create 2 cohorts with the same learning plan template, and when you filter make sure you get only students from the selected cohort, or something like that)
>    If you can add a behat test, it is even better!

As our time budget for this workpackage is quite used up, I will have to check what I can do.

I will come back as soon as I have results, but this will take some time now again on my side.

**Comment by levemar** [comment]
@abias Ok, perfect, thanks for the answer! See what you can do in the time you have, we will wait to hear again from you.

**Comment by abias** [comment]
Hi @levemar ,

I just stumbled upon this pending PR. 
I am really sorry, but the customer who initially ordered this feature lost interest in it. That's why I won't be able to rebase and extend it as requested.

Feel free to take the code and finish the feature yourself or close the PR alternatively.

Cheers,
Alex

**Pull request closed without merging**
